kind: Deployment
apiVersion: apps/v1
metadata:
  name: confvalue
spec:
  replicas: 4
  selector:
    matchLabels:
      tag: confvaluepod
  template:
    metadata:
      labels:
        tag: confvaluepod
    spec:
      containers:
        - name: c89
          image: ubuntu
          command: ["/bin/bash","-c","while true; do echo panchayat seaseon 3 best; sleep 90; done"]
          env:
          - name: MYENV
            valueFrom:
              configMapKeyRef:
                name: mymap
                key: sample.conf