kind: Pod
apiVersion: v1
metadata:
  name: livenessprobe1
  label:
    test: livness
spec:
  containers:
    - name: liveness
      image: ubuntu
      args:
      - /bin/sh
      - -c
      - touch /tmp/healthy; sleep 1000
      livenessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
          initialDelaySeconds: 5
          periodSeconds: 5
          timeOutSeconds: 30
