kind: Pod
apiVersion: v1
metadata:
  name: mulPod
spec:
  containers:
    - name: c40
      image: ubuntu
      command: ["bin/bash","-c","while true; do echo go-ahead; sleep 9 ; done"]
      resources:
        requests:
          ephemeral-storage: "500Mi"
        limits:
          ephemeral-storage: "800Mi"
    - name: c41
      image: centos
      command: ["bin/bash","-c","while true; do echo go-ahead; sleep 9 ; done"]
      resources:  
        requests:
         ephemeral-storage: "500Mi"
        limits:
          ephemeral-storage: "800Mi"
      
