kind: Pod
apiVersion: v1
metadata:
  name: tetpod2
spec:
  containers:
    - name: c00
      image: ubuntu 
      command: ["bin/bash", "-c","while true; do echo yes all corect over; sleep 6 ; done"]
  restartPolicy: Never
<<<<<<< HEAD
   
=======
>>>>>>> 0e4646995ddc9e897f490dfb916ddbc5408f861a
