kind: ReplicationController
apiVersion: v1
metadata:
  name: testreplica
  labels:
    tag: muktisreplica
spec:
  replicas: 5
  selector:
    tag: muktisreplica
  template:
    metadata:
      name: testpod43
      labels:
        tag: muktisreplica
    spec:
      containers:
        - name: p90
          image: 90mukti/web
          command: ["/bin/bash","-c", "while true; do echo all correct bro!!; sleep 9 ; done"]
