kind: Deployment
apiVersion: apps/v1
metadata:
  name: secretdeploy
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: secretpods
  template:
    metadata:
      labels:
        tag: secretpods
    spec:
      containers:
        - name: scrt7
          image: centos
          command: ["/bin/bash","-c","while true; do echo success ful secret; sleep 23 ; done"]
          volumeMounts:
            - name: secretvol
              mountPath: "/tmp/secretdir"
              readOnly: true
      volumes:
        - name: secretvol
          secret:
            secretName: mysecret
