kind: Secret
apiVersion: v1
metadata:
  name: mysecret
type: opaque
data:
  username: AG0AdQBrAHQAaQBrAGEAbgB0AC4AbgBhAG4AZABhAEAAYQB3AHMALgBjAG8AbQ==
  password: ADkAQABLAGkAcwBsAGUAeQByAGEAegB6
